version: "3.3"
#
# Compose for the development of this docker image
#
services:
  database:
    image: "postgres:9.6"
    environment:
      - POSTGRES_USER=omero
      - POSTGRES_DB=omero
      - POSTGRES_PASSWORD=omero
    networks:
      - omero
    volumes:
      - "database:/var/lib/postgresql/data"

  minimal:
    image: ${REPO}/omero-server-minimal:${PREFIX}
    build:
      context: .
      args:
        - OMEGO_ADDITIONAL_ARGS="--ci=https://merge-ci.openmicroscopy.org/jenkins/"
        - OMERO_VERSION="OMERO-build"
    entrypoint: "true"

  omero:
    image: ${REPO}/omero-server:${PREFIX}
    build:
      context: extended
      args:
        - PARENT_IMAGE=${REPO}/omero-server-minimal:${PREFIX}
    environment:
      - CONFIG_omero_db_host=database
      - CONFIG_omero_db_user=omero
      - CONFIG_omero_db_pass=omero
      - CONFIG_omero_db_name=omero
      - ROOTPASS=omero
    networks:
      - omero
    ports:
      - "${TCP_PORT}4063"
      - "${SSL_PORT}4064"
    volumes:
      - "omero:/OMERO"
      - "./:/src:ro"
    depends_on:
      - minimal

networks:
  omero:

volumes:
  database:
  omero:
